### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by LeDeathAmongst**
FIxed a typo. Had serverassistnat not serverassistant

### CODE REVIEW

**Comment by nottherealtar** [comment]
Thank you for your contribution soldier.

**Comment by LeDeathAmongst** [comment]
Want help fixing interactions? Plus, channelmap give error as well

**Comment by LeDeathAmongst** [comment]
```Exception in command 'serverassistant channelmap':

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/serverassistant/serverassistant.py", line 59, in channel_map
    channel_list.sort(key=lambda x: (x.position, x.type))  # Sort channels by position and type
    ^^^^^^^^^^^^^^^^^
AttributeError: 'SequenceProxy' object has no attribute 'sort'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1650, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'SequenceProxy' object has no attribute 'sort'```

**Comment by nottherealtar** [comment]
> Want help fixing interactions? Plus, channelmap give error as well

That would be awesome, I should have added [WIP] to the title but I think one or 2 features worked in the beginning. Please feel free!

**Comment by LeDeathAmongst** [comment]
Okay!

**Comment by LeDeathAmongst** [comment]
what's going on with Count4U? and the others that are [WIP}?

**Comment by LeDeathAmongst** [comment]
DM me on dc if you want to talk some more:
death_waffle

**Pull request merged**
